# Topology 4

network:
  version: 2
  renderer: networkd
  ethernets:     
    eth01:
      macaddress: '00-D0-56-F2-B5-11'
      addresses: '10.8.6.11/24'
      gateway4: '10.8.6.1'
      nameservers:
          addresses: [8.8.8.8]
      