# Topology 4 

network:
  version: 2
  renderer: networkd
  ethernets:     
    eth01:
      macaddress: '00-D0-56-F2-B5-19'
      addresses: '10.8.9.19/24'
      gateway4: '10.8.9.1'
      nameservers:
          addresses: [8.8.8.8]
      
      