# Topology 4 

network:
  version: 2
  renderer: networkd
  ethernets:     
    eth01:
      macaddress: '00-D0-56-F2-B5-07'
      addresses: '10.8.4.7/24'
      gateway4: '10.8.4.1'
      nameservers:
          addresses: [8.8.8.8]
      