# Topology 4 

network:
  version: 2
  renderer: networkd
  ethernets:     
    eth01:
      macaddress: '17-D0-56-F2-B5-01'
      addresses: '100.1.22.1/24'
      nat: 
        status: 'disabled'
        public_ip: '0.0.0.0/24' 
      gateway4: '0.0.0.0'
      nameservers:
        addresses: [8.8.8.8]
    
    eth02:
      macaddress: '17-D0-56-F2-B5-23'
      addresses: '100.1.31.2/24'
      nat: 
        status: 'disabled' 
        public_ip: '0.0.0.0' 
      gateway4: '0.0.0.0'
      nameservers:
        addresses: [8.8.8.8]
    
    eth03:
      macaddress: '17-D0-56-F2-B5-03'
      addresses: '100.1.41.2/24'
      nat: 
        status: 'disabled' 
        public_ip: '0.0.0.0'
      gateway4: '0.0.0.0'
      nameservers:
        addresses: [8.8.8.8]
    
    eth04:
      macaddress: '17-D0-56-F2-B5-04'
      addresses: '100.1.51.1/24'
      nat: 
        status: 'disabled' 
        public_ip: '0.0.0.0'
      gateway4: '0.0.0.0'
      nameservers:
        addresses: [8.8.8.8]
    
    
    rt:
      routes:
        to: ["100.1.8.0/24", "100.1.9.0/24", "0.0.0.0"]
        via: ["100.1.22.8", "100.1.22.8", "100.1.51.2"]