# Topology 4 

network:
  version: 2
  renderer: networkd
  ethernets:     
    eth01:
      macaddress: '01:11:22:33:44:02'
      addresses: '100.1.11.20/24'
      gateway4: '100.1.11.1'
      nameservers:
          addresses: [8.8.8.8]
      